=== gridguyz/core/module/Core/public/styles/schemas/paragraph/1.0.dtd
<!--

    Gridguyz Paragraph XML-based markup language

    Namespace = http://gridguyz.com/#gpml

    This DTD module is identified by the PUBLIC and SYSTEM identifiers:

    PUBLIC "-//Gridguyz//Paragraph 1.0//EN"
    SYSTEM "http://gridguyz.com/styles/schemas/paragraph/1.0.dtd"

    or (if you use at a gridguyz installation) just simply:

    SYSTEM "public/styles/schemas/paragraph/1.0.dtd"

    Version: 1.0
    Author: David Pozsar <david.pozsar@megaweb.hu>

-->

<!--================================= Types =================================-->

<!-- Uniform Resource Identifier, see [RFC2396] -->
<!ENTITY % URI "CDATA">

<!-- Used for names etc. -->
<!ENTITY % Text "CDATA">

<!-- Used for db ids -->
<!ENTITY % Integer "CDATA">

<!-- Version identifiers -->
<!ENTITY % Version "CDATA">

<!-- Date and time information. ISO date format -->
<!ENTITY % Datetime "CDATA">

<!-- Used for css priority -->
<!ENTITY % CssPriority "(important)">

<!--===================== Structure & meta informations =====================-->

<!-- Root tag -->
<!ELEMENT gpml (domain*, paragraph, customize-rule*, customize-extra?)>

<!ATTLIST gpml
    version     %Version;       #REQUIRED
    db-schema   %Text;          #REQUIRED
    created     %Datetime;      #IMPLIED
    xmlns       %URI;           #FIXED      'http://gridguyz.com/#gpml'
>

<!-- Domain tag -->
<!ELEMENT domain (#PCDATA)>

<!--======================== Paragraph-related tags =========================-->

<!-- Paragraph tag -->
<!ELEMENT paragraph ((paragraph|paragraph-property)*)>

<!ATTLIST paragraph
    id          %Integer;       #REQUIRED
    type        %Text;          #REQUIRED
    name        %Text;          #IMPLIED
>

<!-- Paragraph-property tag -->
<!ELEMENT paragraph-property (substitution*)>

<!ATTLIST paragraph-property
    locale      %Text;          #IMPLIED
    name        %Text;          #REQUIRED
    value       %Text;          #IMPLIED
>

<!--======================== Customize-related tags =========================-->

<!-- Customize-rule tag -->
<!ELEMENT customize-rule (customize-property*)>

<!ATTLIST customize-rule
    selector    %Text;          #REQUIRED
    media       %Text;          #IMPLIED
>

<!-- Customize-property tag -->
<!ELEMENT customize-property (substitution*)>

<!ATTLIST customize-property
    name        %Text;          #REQUIRED
    value       %Text;          #IMPLIED
    priority    %CssPriority;   #IMPLIED
>

<!-- Customize-extra tag -->
<!ELEMENT customize-extra (#PCDATA)>

<!--========================== Value-substitutions ==========================-->

<!-- Substitution tag -->
<!ELEMENT substitution EMPTY>

<!ATTLIST substitution
    original    %Text;          #REQUIRED
    file        %Text;          #REQUIRED
>

=== gridguyz/core/module/Core/public/styles/schemas/paragraph/sample.xml
<!DOCTYPE gpml SYSTEM "public/styles/schemas/paragraph/1.0.dtd">
<gpml xmlns="http://gridguyz.com/#gpml"
      version="1.0"
      db-schema="site_source">
    <domain>gridguyz.com</domain>
    <paragraph id="1"
               type="layout"
               name="Sample exported layout">
        <paragraph id="2"
                   type="menu" />
        <paragraph id="3"
                   type="columns">
            <paragraph id="4"
                       type="column">
                <paragraph id="5"
                           type="login">
                    <paragraph-property locale="*"
                                        name="displayRegisterLink"
                                        value="1"/>
                    <paragraph-property locale="*"
                                        name="displayPasswordRequestLink"
                                        value="1"/>
                    <paragraph-property locale="*"
                                        name="displayLoginWithLink"
                                        value="1"/>
                </paragraph>
            </paragraph>
            <paragraph id="6"
                       type="column">
                <paragraph id="7"
                           type="contentPlaceholder" />
            </paragraph>
        </paragraph>
    </paragraph>
    <customize-rule selector="body">
        <customize-property name="font-family"
                            value="&quot;Open Sans&quot;, sans-serif"/>
    </customize-rule>
    <customize-rule selector="#paragraph-1.paragraph.paragraph-layout">
        <customize-property name="width"
                            value="1000px"/>
    </customize-rule>
    <customize-rule selector="#paragraph-4-container.paragraph-container.paragraph-column-container">
        <customize-property name="width"
                            value="25%"
                            priority="important"/>
    </customize-rule>
    <customize-rule selector="#paragraph-6-container.paragraph-container.paragraph-column-container">
        <customize-property name="width"
                            value="75%"
                            priority="important"/>
    </customize-rule>
    <customize-extra>
@font-face
{
    font-family: &quot;Open Sans&quot;;
    font-style: normal;
    font-weight: 400;
    src: local(&quot;Open Sans&quot;),
         local(&quot;OpenSans&quot;),
         url(&quot;http://themes.googleusercontent.com/static/fonts/opensans/v8/cJZKeOuBrn4kERxqtaUH3aCWcynf_cDxXwCLxiixG1c.ttf&quot;) format(&quot;truetype&quot;);
}
    </customize-extra>
</gpml>
